### ISSUE TITLE
Group messages by date

### ISSUE THREAD

**Issue by sangupta** [shagunsodhani/github-summary#3]
Say we have many commits in the last 3 days, it would be nice to have a command line flag to group by date, for example:

```
In repo github.com/sangupta/some-repo:

Jan 5, 2017: Today
    44: 2c0a7e485dd277ff76257adfd82912c6162fa4a9 - some commit msg
    45: c4460c82dbac84c4cd87886bf17d26e68984ab57 - some commit msg
    46: 91aca9866e8cb6ada14284df41cbadebe34c00ef - some commit msg

Jan 4, 2017: yesterday
    47: 855e1db02aabf760c04110ca449708f9c4fbc33d - some commit msg
    48: 37e5a66ee3ebe319cc1a2518d4ca428161eb5e09 - some commit msg
    49: 7f75437e3e365152b745a47bfa2c198446dfe557 - some commit msg

Jan 3, 2017: 2 days back
    50: d07e3e8a5fe7d31ccc7849b82fec4d166ff89f1f - some commit msg
```

**Comment by shagunsodhani** [comment]
Closed due to typo in commit message.

**Comment by shagunsodhani** [comment]
Should we support grouping by date only or by other parameters like hour as well?

**Comment by sangupta** [comment]
I personally don't see a reason to group by hour. By date grouping should help users fill in their daily timesheets with comments easily.

However, I do feel there is an additional use-case: Group by date across all repositories. This should help me see what I did on a certain day across all my repositories.
